set_property PACKAGE_PIN M21 [get_ports clk]
set_property PACKAGE_PIN T22 [get_ports ps2_data]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports ps2_clk]
set_property IOSTANDARD LVCMOS33 [get_ports ps2_data]

set_property PACKAGE_PIN R20 [get_ports ps2_clk]

create_clock -period 20.000 -name clk -waveform {0.000 10.000} [get_ports clk]
create_generated_clock -name ps2_keyboard_0/debounce_ps2_clk/CLK -source [get_ports clk] -divide_by 1 [get_pins ps2_keyboard_0/debounce_ps2_clk/result_reg/Q]

create_interface keyboard_pins
set_property INTERFACE keyboard_pins [get_ports { clk ps2_clk ps2_data }]


set_property MARK_DEBUG true [get_nets ps2_code_new]
set_property MARK_DEBUG true [get_nets clk_IBUF_BUFG]
set_property MARK_DEBUG false [get_nets {ascii[0]}]
set_property MARK_DEBUG false [get_nets {ascii[1]}]
set_property MARK_DEBUG false [get_nets {ascii[2]}]
set_property MARK_DEBUG false [get_nets {ascii[3]}]
set_property MARK_DEBUG false [get_nets {ascii[4]}]
set_property MARK_DEBUG false [get_nets {ascii[5]}]
set_property MARK_DEBUG false [get_nets {ascii[6]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 7 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {ascii[0]} {ascii[1]} {ascii[2]} {ascii[3]} {ascii[4]} {ascii[5]} {ascii[6]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list ps2_code_new]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list clk_IBUF]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]
